### ISSUE TITLE
MemoryError: memory allocation failed, allocating 151 bytes

### ISSUE THREAD

**Issue by fredfanatics** [adafruit/Adafruit_CircuitPython_Crickit#11]
I tried to test my crickit for cpx with two dc-motors. When I try to import 
`from adafruit_crickit import crickit`
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_crickit.py", line 65, in <module>
MemoryError: memory allocation failed, allocating 151 bytes
```

**Comment by fredfanatics** [comment]
Upgrade CPX with [Latest release cpw with crickit](https://github.com/adafruit/circuitpython/releases/download/3.1.1/adafruit-circuitpython-circuitplayground_express_crickit-3.1.1.uf2)
